import 'dart:async';
import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/exam_event_model.dart';
import 'exam_behavior_service.dart';

// ─────────────────────────────────────────────────────────────
//  ExamSessionService — CRUD untuk exam_events & exam_sessions
// ─────────────────────────────────────────────────────────────
class ExamSessionService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // ── References ──────────────────────────────────────────────
  CollectionReference<Map<String, dynamic>> _eventsRef(String schoolId) =>
      _db.collection('schools').doc(schoolId).collection('exam_events');

  CollectionReference<Map<String, dynamic>> _sessionsRef(String schoolId) =>
      _db.collection('schools').doc(schoolId).collection('exam_sessions');

  CollectionReference<Map<String, dynamic>> _participationsRef(
          String schoolId, String sessionId) =>
      _sessionsRef(schoolId).doc(sessionId).collection('participations');

  // ── ExamEvent CRUD ───────────────────────────────────────────

  /// Membuat ExamEvent baru, mengembalikan ID dokumen yang dibuat
  Future<String> createExamEvent({
    required String schoolId,
    required ExamEvent event,
  }) async {
    final docRef = _eventsRef(schoolId).doc();
    final newEvent = ExamEvent(
      id: docRef.id,
      title: event.title,
      examType: event.examType,
      startDate: event.startDate,
      endDate: event.endDate,
      dailySlots: event.dailySlots,
      subjectConfigs: event.subjectConfigs,
      rooms: event.rooms,
      examStatus: 'Planning',
      isAutoGenerated: false,
      createdAt: DateTime.now(),
    );
    await docRef.set(newEvent.toFirestore());
    return docRef.id;
  }

  /// Stream seluruh event UTS/UAS sekolah yang tidak diarsipkan (diurutkan terbaru)
  Stream<List<ExamEvent>> getExamEvents(String schoolId) {
    return _eventsRef(schoolId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) {
          final events = snap.docs
              .map((d) => ExamEvent.fromFirestore(d))
              .where((e) => e.examStatus != 'Archived')
              .toList();
          events.sort((a, b) => b.createdAt.compareTo(a.createdAt));
          return events;
        });
  }

  /// Stream seluruh event UTS/UAS sekolah yang DIARSIPKAN (diurutkan terbaru)
  Stream<List<ExamEvent>> getArchivedExamEvents(String schoolId) {
    return _eventsRef(schoolId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) {
          final events = snap.docs
              .map((d) => ExamEvent.fromFirestore(d))
              .where((e) => e.examStatus == 'Archived')
              .toList();
          events.sort((a, b) => b.createdAt.compareTo(a.createdAt));
          return events;
        });
  }

  /// Stream event yang sedang "Active" (untuk cek kondisi dashboard siswa)
  Stream<ExamEvent?> getActiveExamEvent(String schoolId) {
    return _eventsRef(schoolId)
        .where('examStatus', isEqualTo: 'Active')
        .limit(1)
        .snapshots()
        .map((snap) =>
            snap.docs.isEmpty ? null : ExamEvent.fromFirestore(snap.docs.first));
  }

  /// Stream event ujian terbaru yang active, untuk tampilan kartu siswa
  Stream<ExamEvent?> getLatestExamEvent(String schoolId) {
    return _eventsRef(schoolId)
        .snapshots()
        .map((snap) {
          final events = snap.docs
              .map((d) => ExamEvent.fromFirestore(d))
              .where((e) => e.examStatus == 'Active')
              .toList();
          if (events.isEmpty) return null;
          // Urutkan descending berdasarkan tanggal mulai, ambil yang terbaru
          events.sort((a, b) => b.startDate.compareTo(a.startDate));
          return events.first;
        });
  }

  /// Stream satu event berdasarkan ID
  Stream<ExamEvent?> getExamEventById(String schoolId, String eventId) {
    return _eventsRef(schoolId)
        .doc(eventId)
        .snapshots()
        .map((d) => d.exists ? ExamEvent.fromFirestore(d) : null);
  }

  /// Update status event (Planning → Active → Finished)
  /// Jika status menjadi Active, buat dokumen Exam di collection /exams untuk setiap sesi yang memiliki soal
  Future<void> updateExamEventStatus(
      String schoolId, String eventId, String status) async {
    if (status == 'Active') {
      // 1. Ambil detail event untuk tahu subjectConfigs
      final eventDoc = await _eventsRef(schoolId).doc(eventId).get();
      if (!eventDoc.exists) {
        throw Exception('Event tidak ditemukan.');
      }
      final eventData = eventDoc.data()!;
      final List subjectConfigsList = eventData['subjectConfigs'] as List? ?? [];

      // Build classId -> angkatan mapping from students list
      final studentsSnap = await _db
          .collection('schools')
          .doc(schoolId)
          .collection('students')
          .get();

      final Map<String, Map<String, int>> classAngkatanCounts = {};
      for (final doc in studentsSnap.docs) {
        final data = doc.data();
        final cid = data['classId'] as String? ?? '';
        final angkatan = (data['angkatan'] ?? '').toString().trim();
        final isLulus = data['lulus'] == true;
        final isAktif = data['aktif'] ?? true;
        if (cid.isNotEmpty && angkatan.isNotEmpty && !isLulus && isAktif) {
          classAngkatanCounts.putIfAbsent(cid, () => {});
          classAngkatanCounts[cid]![angkatan] = (classAngkatanCounts[cid]![angkatan] ?? 0) + 1;
        }
      }

      final Map<String, String> classIdToAngkatan = {};
      classAngkatanCounts.forEach((cid, counts) {
        if (counts.isNotEmpty) {
          classIdToAngkatan[cid] = counts.entries.reduce((a, b) => a.value > b.value ? a : b).key;
        }
      });

      // Ambil seluruh sesi untuk event ini
      final sessionsSnap = await _sessionsRef(schoolId)
          .where('eventId', isEqualTo: eventId)
          .get();

      // Group active angkatans by subjectId
      final Map<String, Set<String>> subjectActiveAngkatans = {};
      for (final doc in sessionsSnap.docs) {
        final sData = doc.data();
        final subId = sData['subjectId']?.toString() ?? '';
        final classId = sData['classId']?.toString() ?? '';
        
        final cids = classId.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty);
        for (final cid in cids) {
          final angkatan = classIdToAngkatan[cid] ?? '';
          if (subId.isNotEmpty && angkatan.isNotEmpty) {
            subjectActiveAngkatans.putIfAbsent(subId, () => {}).add(angkatan);
          }
        }
      }

      // Validasi: Cek apakah ada mapel yang belum punya soal untuk angkatan yang berpartisipasi
      final List<String> subjectsWithoutQuestions = [];
      for (final item in subjectConfigsList) {
        final map = Map<String, dynamic>.from(item);
        final subId = map['subjectId']?.toString() ?? '';
        final subName = map['subjectName']?.toString() ?? 'Mata Pelajaran';
        if (subId.isNotEmpty) {
          final activeAngkatans = subjectActiveAngkatans[subId] ?? {};
          
          if (activeAngkatans.isEmpty) continue;
          
          for (final angkatan in activeAngkatans) {
            final docId = '${eventId}_${subId}_$angkatan';
            final qDoc = await _db
                .collection('schools')
                .doc(schoolId)
                .collection('exam_questions')
                .doc(docId)
                .get();
            
            bool hasQuestions = false;
            if (qDoc.exists && qDoc.data() != null) {
              final List questions = qDoc.data()!['questions'] as List? ?? [];
              if (questions.isNotEmpty) {
                hasQuestions = true;
              }
            }
            
            if (!hasQuestions) {
              subjectsWithoutQuestions.add('$subName (Angkatan $angkatan)');
            }
          }
        }
      }

      if (subjectsWithoutQuestions.isNotEmpty) {
        throw Exception(
          'Mata pelajaran berikut belum memiliki soal:\n'
          '${subjectsWithoutQuestions.map((s) => "- $s").join("\n")}',
        );
      }
    }

    // Update status di Firestore setelah validasi berhasil
    await _eventsRef(schoolId).doc(eventId).update({'examStatus': status});

    if (status == 'Finished') {
      try {
        final sessionsSnap = await _sessionsRef(schoolId).where('eventId', isEqualTo: eventId).get();
        for (final doc in sessionsSnap.docs) {
          await ExamBehaviorService().deleteExamBehaviorForSession(
            schoolId: schoolId,
            sessionId: doc.id,
          );
        }
      } catch (e) {
        // Abaikan error jika ada
      }
    }

    if (status == 'Active') {
      // Ambil detail event lagi untuk generate exams
      final eventDoc = await _eventsRef(schoolId).doc(eventId).get();
      if (!eventDoc.exists) return;
      final eventData = eventDoc.data()!;
      final examType = eventData['examType']?.toString() ?? 'UTS';
      final title = eventData['title']?.toString() ?? '';

      // Map subjectConfigs agar gampang diakses
      final List subjectConfigsList = eventData['subjectConfigs'] as List? ?? [];
      final Map<String, Map<String, dynamic>> subjectConfigsMap = {};
      for (final item in subjectConfigsList) {
        final map = Map<String, dynamic>.from(item);
        final subId = map['subjectId']?.toString() ?? '';
        if (subId.isNotEmpty) {
          subjectConfigsMap[subId] = map;
        }
      }

      // Ambil tahunAjaran dan semester dari school metadata
      final schoolDoc = await _db.collection('schools').doc(schoolId).get();
      final schoolData = schoolDoc.data() ?? {};
      final tahunAjaran = schoolData['tahunAjaran']?.toString() ?? '';
      final semester = schoolData['semester']?.toString() ?? '';

      // Build classId -> angkatan mapping from students list
      final studentsSnap = await _db
          .collection('schools')
          .doc(schoolId)
          .collection('students')
          .get();

      final Map<String, Map<String, int>> classAngkatanCounts = {};
      for (final doc in studentsSnap.docs) {
        final data = doc.data();
        final cid = data['classId'] as String? ?? '';
        final angkatan = (data['angkatan'] ?? '').toString().trim();
        final isLulus = data['lulus'] == true;
        final isAktif = data['aktif'] ?? true;
        if (cid.isNotEmpty && angkatan.isNotEmpty && !isLulus && isAktif) {
          classAngkatanCounts.putIfAbsent(cid, () => {});
          classAngkatanCounts[cid]![angkatan] = (classAngkatanCounts[cid]![angkatan] ?? 0) + 1;
        }
      }

      final Map<String, String> classIdToAngkatan = {};
      classAngkatanCounts.forEach((cid, counts) {
        if (counts.isNotEmpty) {
          classIdToAngkatan[cid] = counts.entries.reduce((a, b) => a.value > b.value ? a : b).key;
        }
      });

      // 2. Ambil semua sesi untuk event ini
      final sessionsSnap = await _sessionsRef(schoolId)
          .where('eventId', isEqualTo: eventId)
          .get();

      for (final sDoc in sessionsSnap.docs) {
        final sData = sDoc.data();
        final subjectId = sData['subjectId']?.toString() ?? '';
        final subjectName = sData['subjectName']?.toString() ?? '';
        final classId = sData['classId']?.toString() ?? '';
        final className = sData['className']?.toString() ?? '';

        // Dapatkan corrector/author ids & names dari config
        final config = subjectConfigsMap[subjectId];
        List<String> authorIds = [];
        List<String> authorNames = [];
        if (config != null) {
          if (config['authorTeacherIds'] != null) {
            authorIds = List<String>.from(config['authorTeacherIds']);
          } else if (config['authorTeacherId'] != null && config['authorTeacherId'].toString().isNotEmpty) {
            authorIds = [config['authorTeacherId'].toString()];
          }

          if (config['authorTeacherNames'] != null) {
            authorNames = List<String>.from(config['authorTeacherNames']);
          } else if (config['authorTeacherName'] != null && config['authorTeacherName'].toString().isNotEmpty) {
            authorNames = [config['authorTeacherName'].toString()];
          }
        }

        // Tentukan durasi
        int duration = 90;
        try {
          final start = sData['startTime']?.toString() ?? '07:30';
          final end = sData['endTime']?.toString() ?? '09:00';
          final startParts = start.split(':');
          final endParts = end.split(':');
          final startMin = int.parse(startParts[0]) * 60 + int.parse(startParts[1]);
          final endMin = int.parse(endParts[0]) * 60 + int.parse(endParts[1]);
          if (endMin > startMin) {
            duration = endMin - startMin;
          }
        } catch (_) {}

        // Ambil questions dari exam_questions/${eventId}_${subjectId}_${angkatan} atau fallback ke ${eventId}_${subjectId}
        final firstClassId = classId.split(',').first.trim();
        var angkatan = classIdToAngkatan[firstClassId] ?? '';
        if (angkatan.isEmpty) {
          final lvl = _getGradeLevel(className);
          if (lvl == '3') {
            angkatan = '2020';
          } else if (lvl == '2') {
            angkatan = '2021';
          } else if (lvl == '1') {
            angkatan = '2022';
          } else {
            angkatan = '2022';
          }
        }

        var qDoc = await _db
            .collection('schools')
            .doc(schoolId)
            .collection('exam_questions')
            .doc('${eventId}_${subjectId}_$angkatan')
            .get();

        if (!qDoc.exists || qDoc.data() == null) {
          qDoc = await _db
              .collection('schools')
              .doc(schoolId)
              .collection('exam_questions')
              .doc('${eventId}_$subjectId')
              .get();
        }

        if (qDoc.exists && qDoc.data() != null) {
          final qData = qDoc.data()!;
          final questionsList = qData['questions'] as List? ?? [];

          // Buat ID exam: eventId_subjectId_classId
          final examId = '${eventId}_${subjectId}_$classId';

          // Tulis ke collection /exams
          await _db
              .collection('schools')
              .doc(schoolId)
              .collection('exams')
              .doc(examId)
              .set({
            'title': '$examType $subjectName - $className',
            'description': 'Ujian Semester $examType - $title',
            'classId': classId,
            'className': className,
            'subjectId': subjectId,
            'subjectName': subjectName,
            'teacherId': authorIds.isNotEmpty ? authorIds.first : '',
            'teacherName': authorNames.isNotEmpty ? authorNames.join(', ') : 'Guru Penguji',
            'teacherIds': authorIds,
            'teacherNames': authorNames,
            'durationMinutes': duration,
            'syncToGrades': true,
            'gradeCategory': examType, // UTS atau UAS
            'tahunAjaran': tahunAjaran,
            'semester': semester,
            'createdAt': FieldValue.serverTimestamp(),
            'dueDate': Timestamp.fromDate((sData['date'] as Timestamp).toDate().add(const Duration(days: 1))),
            'status': 'active',
            'questions': questionsList,
            'susulanStudentIds': [],
          });
        }
      }
    }
  }

  /// Hapus event beserta seluruh sesinya (batch delete)
  Future<void> deleteExamEvent(String schoolId, String eventId) async {
    final List<DocumentReference> refsToDelete = [];

    // 1. Hapus semua sesi terkait (termasuk sub-koleksi participations)
    final sessions = await _sessionsRef(schoolId)
        .where('eventId', isEqualTo: eventId)
        .get();
    for (final sDoc in sessions.docs) {
      // Hapus participations dalam setiap sesi
      final parts = await sDoc.reference.collection('participations').get();
      for (final pDoc in parts.docs) {
        refsToDelete.add(pDoc.reference);
      }
      refsToDelete.add(sDoc.reference);

      // Bersihkan juga behavior records jika masih ada
      try {
        await ExamBehaviorService().deleteExamBehaviorForSession(
          schoolId: schoolId,
          sessionId: sDoc.id,
        );
      } catch (e) {
        // Abaikan
      }
    }

    // 2. Hapus exams yang digenerate oleh event ini
    final examsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('exams')
        .where(FieldPath.documentId, isGreaterThanOrEqualTo: '${eventId}_')
        .where(FieldPath.documentId, isLessThanOrEqualTo: '${eventId}_\uf8ff')
        .get();
    for (final doc in examsSnap.docs) {
      refsToDelete.add(doc.reference);
    }

    // 3. Hapus exam_questions (bank soal) terkait event ini
    final questionsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('exam_questions')
        .where(FieldPath.documentId, isGreaterThanOrEqualTo: '${eventId}_')
        .where(FieldPath.documentId, isLessThanOrEqualTo: '${eventId}_\uf8ff')
        .get();
    for (final doc in questionsSnap.docs) {
      refsToDelete.add(doc.reference);
    }

    // 4. Hapus grades terkait yang di-generate oleh event ini (termasuk kelas gabungan)
    final gradesSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('grades')
        .where(FieldPath.documentId, isGreaterThanOrEqualTo: '${eventId}_')
        .where(FieldPath.documentId, isLessThanOrEqualTo: '${eventId}_\uf8ff')
        .get();
    for (final doc in gradesSnap.docs) {
      refsToDelete.add(doc.reference);
    }

    // 5. Hapus exam submissions terkait event ini
    final submissionsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('exam_submissions')
        .where(FieldPath.documentId, isGreaterThanOrEqualTo: '${eventId}_')
        .where(FieldPath.documentId, isLessThanOrEqualTo: '${eventId}_\uf8ff')
        .get();
    for (final doc in submissionsSnap.docs) {
      refsToDelete.add(doc.reference);
    }

    // 6. Hapus event document itu sendiri
    refsToDelete.add(_eventsRef(schoolId).doc(eventId));

    // Eksekusi penghapusan dalam chunk berukuran maksimal 400 dokumen per batch
    for (int i = 0; i < refsToDelete.length; i += 400) {
      final chunk = refsToDelete.sublist(
        i,
        i + 400 > refsToDelete.length ? refsToDelete.length : i + 400,
      );
      final chunkBatch = _db.batch();
      for (final ref in chunk) {
        chunkBatch.delete(ref);
      }
      await chunkBatch.commit();
    }
  }

  // ── ExamSession CRUD ─────────────────────────────────────────

  /// Menyimpan list ExamSession hasil generate ke Firestore beserta participations-nya
  Future<void> saveGeneratedSessions(
      String schoolId, List<ExamSession> sessions) async {
    for (final session in sessions) {
      final sessionRef = _sessionsRef(schoolId).doc();
      final batch = _db.batch();
      
      // Simpan session
      batch.set(sessionRef, session.toFirestore());
      
      // Simpan draf presensi & kursi jika ada
      if (session.previewParticipations != null) {
        for (final p in session.previewParticipations!) {
          final pRef = sessionRef.collection('participations').doc(p.studentId);
          batch.set(pRef, p.toFirestore());
        }
      }
      
      await batch.commit();
    }
  }

  /// Stream semua sesi untuk satu event
  Stream<List<ExamSession>> getSessionsByEvent(
      String schoolId, String eventId) {
    return _sessionsRef(schoolId)
        .where('eventId', isEqualTo: eventId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi yang ditugaskan ke pengawas tertentu (Guru tetap dapat melihat meskipun event masih Planning)
  Stream<List<ExamSession>> getSessionsByProctor(
      String schoolId, String proctorId) {
    return _sessionsRef(schoolId)
        .where('proctorId', isEqualTo: proctorId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi yang guru bersangkutan menjadi author soal (Guru tetap dapat melihat meskipun event masih Planning)
  Stream<List<ExamSession>> getSessionsByAuthor(
      String schoolId, String authorTeacherId) {
    return _sessionsRef(schoolId)
        .snapshots()
        .map((snap) {
          final list = snap.docs
              .map((d) => ExamSession.fromFirestore(d))
              .where((s) => s.authorTeacherId.split(',').contains(authorTeacherId))
              .toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi untuk kelas tertentu (hanya jika event-nya Active, bukan Planning atau Finished)
  Stream<List<ExamSession>> getSessionsByClass(
      String schoolId, String classId) {
    final controller = StreamController<List<ExamSession>>();
    StreamSubscription? subEvents;
    StreamSubscription? subSessions;

    List<ExamEvent> events = [];
    List<ExamSession> sessions = [];

    void update() {
      if (controller.isClosed) return;
      final activeEventIds = events
          .where((e) => e.examStatus != 'Planning' && 
                        e.examStatus != 'Finished' && 
                        e.examStatus.toLowerCase() != 'archived')
          .map((e) => e.id)
          .toSet();
      final filtered = sessions
          .where((s) => s.classId.split(',').map((e) => e.trim()).contains(classId) &&
                        activeEventIds.contains(s.eventId))
          .toList();
      controller.add(filtered);
    }

    subEvents = _eventsRef(schoolId).snapshots().listen((eventSnap) {
      events = eventSnap.docs.map((d) => ExamEvent.fromFirestore(d)).toList();
      update();
    }, onError: controller.addError);

    subSessions = _sessionsRef(schoolId).snapshots().listen((sessionSnap) {
      sessions = sessionSnap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
      sessions.sort((a, b) => a.date.compareTo(b.date));
      update();
    }, onError: controller.addError);

    controller.onCancel = () {
      subEvents?.cancel();
      subSessions?.cancel();
    };

    return controller.stream;
  }

  /// Cari sessionId yang benar untuk murid berdasarkan record partisipasi.
  /// Dari beberapa sesi yang memiliki subjectId+date+slotName yang sama,
  /// kembalikan sessionId sesi di mana murid memiliki dokumen participation.
  Future<String?> getCorrectSessionIdForStudent({
    required String schoolId,
    required String classId,
    required String studentId,
    required String subjectId,
    required DateTime date,
    required String slotName,
  }) async {
    final dateStr = date.toIso8601String().substring(0, 10);
    final snap = await _sessionsRef(schoolId)
        .where('subjectId', isEqualTo: subjectId)
        .get();

    final candidates = snap.docs
        .map((d) => ExamSession.fromFirestore(d))
        .where((s) =>
            s.classId.split(',').map((e) => e.trim()).contains(classId) &&
            s.date.toIso8601String().substring(0, 10) == dateStr &&
            s.slotName == slotName)
        .toList();

    // Cari sesi di mana murid punya participation doc
    for (final s in candidates) {
      final pDoc = await _participationsRef(schoolId, s.id).doc(studentId).get();
      if (pDoc.exists) return s.id;
    }

    // Fallback: kembalikan sessionId pertama
    return candidates.isNotEmpty ? candidates.first.id : null;
  }

  /// Admin manual override pengawas
  Future<void> updateSessionProctor({
    required String schoolId,
    required String sessionId,
    required String newProctorId,
    required String newProctorName,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'proctorId': newProctorId,
      'proctorName': newProctorName,
    });
  }

  /// Admin update nama ruangan
  Future<void> updateSessionRoom({
    required String schoolId,
    required String sessionId,
    required String roomName,
  }) async {
    await _sessionsRef(schoolId)
        .doc(sessionId)
        .update({'roomName': roomName});
  }

  /// Pengawas mengaktifkan QR (mulai sesi)
  Future<void> activateSessionQr({
    required String schoolId,
    required String sessionId,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'isQrActive': true,
      'examStatus': 'Active',
    });
  }

  /// Pengawas menutup sesi
  Future<void> finishSession({
    required String schoolId,
    required String sessionId,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'isQrActive': false,
      'examStatus': 'Finished',
    });

    // Hapus seluruh behavior records murid untuk sesi ujian ini
    await ExamBehaviorService().deleteExamBehaviorForSession(
      schoolId: schoolId,
      sessionId: sessionId,
    );
  }

  /// Stream satu sesi secara real-time (untuk polling status QR)
  Stream<ExamSession?> getSessionStream(String schoolId, String sessionId) {
    return _sessionsRef(schoolId)
        .doc(sessionId)
        .snapshots()
        .map((d) => d.exists ? ExamSession.fromFirestore(d) : null);
  }

  // ── Participation CRUD ───────────────────────────────────────

  /// Mencatat kehadiran siswa dari sisi pengawas (dengan validasi)
  Future<void> recordProctorScanAttendance({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    final docRef = _participationsRef(schoolId, sessionId).doc(studentId);
    final doc = await docRef.get();
    if (!doc.exists) {
      throw Exception('Murid tidak terdaftar di ruangan / sesi ujian ini!');
    }
    await docRef.set({
      'scannedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// Menghapus / membatalkan kehadiran siswa dari sisi pengawas
  Future<void> cancelProctorScanAttendance({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    final docRef = _participationsRef(schoolId, sessionId).doc(studentId);
    final doc = await docRef.get();
    if (!doc.exists) {
      throw Exception('Murid tidak terdaftar di ruangan / sesi ujian ini!');
    }
    await docRef.set({
      'scannedAt': null,
    }, SetOptions(merge: true));
  }

  /// Mencatat kehadiran siswa setelah scan QR (idempotent)
  Future<void> recordParticipation({
    required String schoolId,
    required String sessionId,
    required String studentId,
    required String studentName,
    required String nis,
  }) async {
    await _participationsRef(schoolId, sessionId).doc(studentId).set({
      'studentId': studentId,
      'studentName': studentName,
      'nis': nis,
      'scannedAt': FieldValue.serverTimestamp(),
      'hasStarted': false,
    }, SetOptions(merge: true));
  }

  /// Cek apakah siswa sudah scan (untuk gate tombol "Mulai Ujian")
  Future<bool> hasStudentScanned({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    final doc = await _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .get();
    if (!doc.exists) return false;
    return doc.data()?['scannedAt'] != null;
  }

  /// Stream real-time participation siswa tertentu
  Stream<ExamParticipation?> getParticipationStream({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) {
    return _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .snapshots()
        .map((d) => d.exists ? ExamParticipation.fromFirestore(d) : null);
  }

  /// Fetch participation sekali (non-stream), digunakan untuk prefetch cache
  Future<ExamParticipation?> getParticipationOnce({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    final doc = await _participationsRef(schoolId, sessionId).doc(studentId).get();
    if (!doc.exists) return null;
    return ExamParticipation.fromFirestore(doc);
  }

  /// Stream seluruh peserta sesi (untuk proctor dashboard)
  Stream<List<ExamParticipation>> getParticipations({
    required String schoolId,
    required String sessionId,
  }) {
    return _participationsRef(schoolId, sessionId)
        .snapshots()
        .map((snap) =>
            snap.docs.map((d) => ExamParticipation.fromFirestore(d)).toList());
  }

  /// Cek apakah murid memiliki minimal satu jadwal ujian (terdaftar di participations)
  Future<bool> hasAnyActiveExamSchedule({
    required String schoolId,
    required String classId,
    required String studentId,
  }) async {
    try {
      final sessionsSnap = await _sessionsRef(schoolId).get();
      final List<ExamSession> sessions = sessionsSnap.docs
          .map((d) => ExamSession.fromFirestore(d))
          .where((s) => s.classId.split(',').map((e) => e.trim()).contains(classId))
          .where((s) {
            final status = s.examStatus.toLowerCase().trim();
            return status != 'finished' && status != 'selesai' && status != 'archived';
          })
          .toList();

      if (sessions.isEmpty) return false;

      final futures = sessions.map((s) => _participationsRef(schoolId, s.id).doc(studentId).get());
      final results = await Future.wait(futures);

      return results.any((doc) => doc.exists);
    } catch (e) {
      return false;
    }
  }


  /// Update status hasStarted siswa setelah mulai ujian
  Future<void> markStudentStarted({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    await _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .update({'hasStarted': true});
  }


  // ── Utility ──────────────────────────────────────────────────

  /// Generate UUID v4 sederhana untuk qrToken
  static String generateQrToken() {
    final rng = Random.secure();
    final bytes = List<int>.generate(16, (_) => rng.nextInt(256));
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    String hex(int n) => n.toRadixString(16).padLeft(2, '0');
    return '${hex(bytes[0])}${hex(bytes[1])}${hex(bytes[2])}${hex(bytes[3])}'
        '-${hex(bytes[4])}${hex(bytes[5])}'
        '-${hex(bytes[6])}${hex(bytes[7])}'
        '-${hex(bytes[8])}${hex(bytes[9])}'
        '-${hex(bytes[10])}${hex(bytes[11])}${hex(bytes[12])}${hex(bytes[13])}${hex(bytes[14])}${hex(bytes[15])}';
  }

  // ── Seat Distribution per existing session ────────────────────

  /// Distribusi kursi selang-seling untuk sesi yang sudah ada di Firestore.
  /// Menghapus data participations lama, lalu generate ulang dari daftar rooms yang diberikan.
  /// Algoritma: siswa 2 angkatan berbeda diinterleave (ganjil=angkatan A, genap=angkatan B).
  Future<void> distributeSeatsForExistingSession({
    required String schoolId,
    required String sessionId,
    required String classId,
    required List<ExamRoom> rooms,
  }) async {
    // 1. Fetch students in this class (handles comma-separated classIds)
    final List<String> targetClassIds = classId.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
    final List<Map<String, dynamic>> allStudents = [];

    for (final cid in targetClassIds) {
      final studentsSnap = await _db
          .collection('schools')
          .doc(schoolId)
          .collection('students')
          .where('classId', isEqualTo: cid)
          .get();

      allStudents.addAll(studentsSnap.docs.map((d) {
        final data = d.data();
        return {
          'id': d.id,
          'nama': data['nama'] ?? '',
          'nis': data['nis'] ?? '',
          'angkatan': (data['angkatan'] ?? '').toString().trim(),
        };
      }));
    }

    // 2. Group by angkatan
    final Map<String, List<Map<String, dynamic>>> byAngkatan = {};
    for (final s in allStudents) {
      final a = (s['angkatan'] as String).isNotEmpty ? s['angkatan'] as String : '-';
      byAngkatan.putIfAbsent(a, () => []).add(s);
    }

    // Sort: biggest cohort first for list A
    final sortedAngkatans = byAngkatan.keys.toList()
      ..sort((a, b) => byAngkatan[b]!.length.compareTo(byAngkatan[a]!.length));

    List<Map<String, dynamic>> listA = [];
    List<Map<String, dynamic>> listB = [];

    if (sortedAngkatans.isNotEmpty) {
      listA = List.from(byAngkatan[sortedAngkatans[0]]!)..shuffle();
    }
    if (sortedAngkatans.length > 1) {
      for (int i = 1; i < sortedAngkatans.length; i++) {
        listB.addAll(byAngkatan[sortedAngkatans[i]]!);
      }
      listB.shuffle();
    }

    // 3. Build participation list (interleaved by room)
    final List<ExamParticipation> participations = [];
    int indexA = 0;
    int indexB = 0;

    for (final room in rooms) {
      for (int seat = 1; seat <= room.capacity; seat++) {
        if (indexA >= listA.length && indexB >= listB.length) break;

        Map<String, dynamic>? picked;
        if (seat % 2 != 0) {
          picked = indexA < listA.length ? listA[indexA++] : (indexB < listB.length ? listB[indexB++] : null);
        } else {
          picked = indexB < listB.length ? listB[indexB++] : (indexA < listA.length ? listA[indexA++] : null);
        }

        if (picked != null) {
          participations.add(ExamParticipation(
            studentId: picked['id'] as String,
            studentName: picked['nama'] as String,
            nis: picked['nis'] as String,
            hasStarted: false,
            seatNumber: seat,
            roomName: room.name,
            angkatan: picked['angkatan'] as String,
          ));
        }
      }
    }

    // 4. Batch write: delete old participations, write new
    final pRef = _participationsRef(schoolId, sessionId);

    // Delete existing participations
    final existingDocs = await pRef.get();
    final batch = _db.batch();
    for (final doc in existingDocs.docs) {
      batch.delete(doc.reference);
    }

    // Write new participations
    for (final p in participations) {
      batch.set(pRef.doc(p.studentId), p.toFirestore());
    }

    // Update session roomName
    final roomNameStr = rooms.map((r) => r.name).join(', ');
    batch.update(_sessionsRef(schoolId).doc(sessionId), {'roomName': roomNameStr});

    await batch.commit();
  }

  /// Sinkronkan/deploy pertanyaan ujian ke koleksi /exams untuk seluruh sesi yang sesuai dengan eventId & subjectId
  Future<void> syncQuestionsToExams({
    required String schoolId,
    required String eventId,
    required String subjectId,
    required List<Map<String, dynamic>> questionsList,
    String? gradeLevel,
  }) async {
    // 1. Ambil detail event
    final eventDoc = await _eventsRef(schoolId).doc(eventId).get();
    if (!eventDoc.exists) return;
    final eventData = eventDoc.data()!;
    final examType = eventData['examType']?.toString() ?? 'UTS';
    final title = eventData['title']?.toString() ?? '';

    // Map subjectConfigs agar gampang diakses
    final List subjectConfigsList = eventData['subjectConfigs'] as List? ?? [];
    final Map<String, Map<String, dynamic>> subjectConfigsMap = {};
    for (final item in subjectConfigsList) {
      final map = Map<String, dynamic>.from(item);
      final subId = map['subjectId']?.toString() ?? '';
      if (subId.isNotEmpty) {
        subjectConfigsMap[subId] = map;
      }
    }

    // Ambil tahunAjaran dan semester dari school metadata
    final schoolDoc = await _db.collection('schools').doc(schoolId).get();
    final schoolData = schoolDoc.data() ?? {};
    final tahunAjaran = schoolData['tahunAjaran']?.toString() ?? '';
    final semester = schoolData['semester']?.toString() ?? '';

    // Build classId -> angkatan mapping from students list
    final studentsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('students')
        .get();

    final Map<String, Map<String, int>> classAngkatanCounts = {};
    for (final doc in studentsSnap.docs) {
      final data = doc.data();
      final cid = data['classId'] as String? ?? '';
      final angkatan = (data['angkatan'] ?? '').toString().trim();
      final isLulus = data['lulus'] == true;
      final isAktif = data['aktif'] ?? true;
      if (cid.isNotEmpty && angkatan.isNotEmpty && !isLulus && isAktif) {
        classAngkatanCounts.putIfAbsent(cid, () => {});
        classAngkatanCounts[cid]![angkatan] = (classAngkatanCounts[cid]![angkatan] ?? 0) + 1;
      }
    }

    final Map<String, String> classIdToAngkatan = {};
    classAngkatanCounts.forEach((cid, counts) {
      if (counts.isNotEmpty) {
        classIdToAngkatan[cid] = counts.entries.reduce((a, b) => a.value > b.value ? a : b).key;
      }
    });

    // 2. Ambil seluruh sesi untuk event dan subject ini
    final sessionsSnap = await _sessionsRef(schoolId)
        .where('eventId', isEqualTo: eventId)
        .where('subjectId', isEqualTo: subjectId)
        .get();

    for (final sDoc in sessionsSnap.docs) {
      final sData = sDoc.data();
      final subjectName = sData['subjectName']?.toString() ?? '';
      final classId = sData['classId']?.toString() ?? '';
      final className = sData['className']?.toString() ?? '';

      final firstClassId = classId.split(',').first.trim();
      var sessionAngkatan = classIdToAngkatan[firstClassId] ?? '';
      if (sessionAngkatan.isEmpty) {
        final lvl = _getGradeLevel(className);
        if (lvl == '3') {
          sessionAngkatan = '2020';
        } else if (lvl == '2') {
          sessionAngkatan = '2021';
        } else if (lvl == '1') {
          sessionAngkatan = '2022';
        } else {
          sessionAngkatan = '2022';
        }
      }
      // Skip if gradeLevel filter is specified and doesn't match this class grade level (angkatan)
      if (gradeLevel != null && sessionAngkatan != gradeLevel) {
        continue;
      }

      // Dapatkan corrector/author ids & names dari config
      final config = subjectConfigsMap[subjectId];
      List<String> authorIds = [];
      List<String> authorNames = [];
      if (config != null) {
        if (config['authorTeacherIds'] != null) {
          authorIds = List<String>.from(config['authorTeacherIds']);
        } else if (config['authorTeacherId'] != null && config['authorTeacherId'].toString().isNotEmpty) {
          authorIds = [config['authorTeacherId'].toString()];
        }

        if (config['authorTeacherNames'] != null) {
          authorNames = List<String>.from(config['authorTeacherNames']);
        } else if (config['authorTeacherName'] != null && config['authorTeacherName'].toString().isNotEmpty) {
          authorNames = [config['authorTeacherName'].toString()];
        }
      }

      // Tentukan durasi
      int duration = 90;
      try {
        final start = sData['startTime']?.toString() ?? '07:30';
        final end = sData['endTime']?.toString() ?? '09:00';
        final startParts = start.split(':');
        final endParts = end.split(':');
        final startMin = int.parse(startParts[0]) * 60 + int.parse(startParts[1]);
        final endMin = int.parse(endParts[0]) * 60 + int.parse(endParts[1]);
        if (endMin > startMin) {
          duration = endMin - startMin;
        }
      } catch (_) {}

      // Buat ID exam: eventId_subjectId_classId
      final examId = '${eventId}_${subjectId}_$classId';

      // Tulis atau update ke collection /exams
      await _db
          .collection('schools')
          .doc(schoolId)
          .collection('exams')
          .doc(examId)
          .set({
        'title': '$examType $subjectName - $className',
        'description': 'Ujian Semester $examType - $title',
        'classId': classId,
        'className': className,
        'subjectId': subjectId,
        'subjectName': subjectName,
        'teacherId': authorIds.isNotEmpty ? authorIds.first : '',
        'teacherName': authorNames.isNotEmpty ? authorNames.join(', ') : 'Guru Penguji',
        'teacherIds': authorIds,
        'teacherNames': authorNames,
        'durationMinutes': duration,
        'syncToGrades': true,
        'gradeCategory': examType, // UTS atau UAS
        'tahunAjaran': tahunAjaran,
        'semester': semester,
        'createdAt': FieldValue.serverTimestamp(),
        'dueDate': Timestamp.fromDate((sData['date'] as Timestamp).toDate().add(const Duration(days: 1))),
        'status': 'active',
        'questions': questionsList,
        'susulanStudentIds': [],
      });
    }
  }
}

String _getGradeLevel(String className) {
  final cleanName = className.toUpperCase().trim();
  if (cleanName.startsWith('XII') || cleanName.contains('12')) return '3';
  if (cleanName.startsWith('XI') || cleanName.contains('11')) {
    if (!cleanName.startsWith('XII')) return '2';
  }
  if (cleanName.startsWith('X') || cleanName.contains('10')) {
    if (!cleanName.startsWith('XII') && !cleanName.startsWith('XI')) return '1';
  }
  if (cleanName.startsWith('IX') || cleanName.contains('9')) return '3';
  if (cleanName.startsWith('VIII') || cleanName.contains('8')) return '2';
  if (cleanName.startsWith('VII') || cleanName.contains('7')) {
    if (!cleanName.startsWith('VIII')) return '1';
  }
  if (cleanName.contains('6')) return '6';
  if (cleanName.contains('5')) return '5';
  if (cleanName.contains('4')) return '4';
  if (cleanName.contains('3')) return '3';
  if (cleanName.contains('2')) return '2';
  return '1';
}
