import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/exam_event_model.dart';

// ─────────────────────────────────────────────────────────────
//  ExamSessionService — CRUD untuk exam_events & exam_sessions
// ─────────────────────────────────────────────────────────────
class ExamSessionService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // ── References ──────────────────────────────────────────────
  CollectionReference<Map<String, dynamic>> _eventsRef(String schoolId) =>
      _db.collection('schools').doc(schoolId).collection('exam_events');

  CollectionReference<Map<String, dynamic>> _sessionsRef(String schoolId) =>
      _db.collection('schools').doc(schoolId).collection('exam_sessions');

  CollectionReference<Map<String, dynamic>> _participationsRef(
          String schoolId, String sessionId) =>
      _sessionsRef(schoolId).doc(sessionId).collection('participations');

  // ── ExamEvent CRUD ───────────────────────────────────────────

  /// Membuat ExamEvent baru, mengembalikan ID dokumen yang dibuat
  Future<String> createExamEvent({
    required String schoolId,
    required ExamEvent event,
  }) async {
    final docRef = _eventsRef(schoolId).doc();
    final newEvent = ExamEvent(
      id: docRef.id,
      title: event.title,
      examType: event.examType,
      startDate: event.startDate,
      endDate: event.endDate,
      dailySlots: event.dailySlots,
      subjectConfigs: event.subjectConfigs,
      rooms: event.rooms,
      examStatus: 'Planning',
      isAutoGenerated: false,
      createdAt: DateTime.now(),
    );
    await docRef.set(newEvent.toFirestore());
    return docRef.id;
  }

  /// Stream seluruh event UTS/UAS sekolah (diurutkan terbaru)
  Stream<List<ExamEvent>> getExamEvents(String schoolId) {
    return _eventsRef(schoolId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) =>
            snap.docs.map((d) => ExamEvent.fromFirestore(d)).toList());
  }

  /// Stream event yang sedang "Active" (untuk cek kondisi dashboard siswa)
  Stream<ExamEvent?> getActiveExamEvent(String schoolId) {
    return _eventsRef(schoolId)
        .where('examStatus', isEqualTo: 'Active')
        .limit(1)
        .snapshots()
        .map((snap) =>
            snap.docs.isEmpty ? null : ExamEvent.fromFirestore(snap.docs.first));
  }

  /// Stream satu event berdasarkan ID
  Stream<ExamEvent?> getExamEventById(String schoolId, String eventId) {
    return _eventsRef(schoolId)
        .doc(eventId)
        .snapshots()
        .map((d) => d.exists ? ExamEvent.fromFirestore(d) : null);
  }

  /// Update status event (Planning → Active → Finished)
  /// Jika status menjadi Active, buat dokumen Exam di collection /exams untuk setiap sesi yang memiliki soal
  Future<void> updateExamEventStatus(
      String schoolId, String eventId, String status) async {
    await _eventsRef(schoolId).doc(eventId).update({'examStatus': status});

    if (status == 'Active') {
      // 1. Ambil detail event untuk tahu examType, dll.
      final eventDoc = await _eventsRef(schoolId).doc(eventId).get();
      if (!eventDoc.exists) return;
      final eventData = eventDoc.data()!;
      final examType = eventData['examType']?.toString() ?? 'UTS';
      final title = eventData['title']?.toString() ?? '';

      // Map subjectConfigs agar gampang diakses
      final List subjectConfigsList = eventData['subjectConfigs'] as List? ?? [];
      final Map<String, Map<String, dynamic>> subjectConfigsMap = {};
      for (final item in subjectConfigsList) {
        final map = Map<String, dynamic>.from(item);
        final subId = map['subjectId']?.toString() ?? '';
        if (subId.isNotEmpty) {
          subjectConfigsMap[subId] = map;
        }
      }

      // Ambil tahunAjaran dan semester dari school metadata
      final schoolDoc = await _db.collection('schools').doc(schoolId).get();
      final schoolData = schoolDoc.data() ?? {};
      final tahunAjaran = schoolData['tahunAjaran']?.toString() ?? '';
      final semester = schoolData['semester']?.toString() ?? '';

      // 2. Ambil semua sesi untuk event ini
      final sessionsSnap = await _sessionsRef(schoolId)
          .where('eventId', isEqualTo: eventId)
          .get();

      for (final sDoc in sessionsSnap.docs) {
        final sData = sDoc.data();
        final subjectId = sData['subjectId']?.toString() ?? '';
        final subjectName = sData['subjectName']?.toString() ?? '';
        final classId = sData['classId']?.toString() ?? '';
        final className = sData['className']?.toString() ?? '';

        // Dapatkan corrector/author ids & names dari config
        final config = subjectConfigsMap[subjectId];
        List<String> authorIds = [];
        List<String> authorNames = [];
        if (config != null) {
          if (config['authorTeacherIds'] != null) {
            authorIds = List<String>.from(config['authorTeacherIds']);
          } else if (config['authorTeacherId'] != null && config['authorTeacherId'].toString().isNotEmpty) {
            authorIds = [config['authorTeacherId'].toString()];
          }

          if (config['authorTeacherNames'] != null) {
            authorNames = List<String>.from(config['authorTeacherNames']);
          } else if (config['authorTeacherName'] != null && config['authorTeacherName'].toString().isNotEmpty) {
            authorNames = [config['authorTeacherName'].toString()];
          }
        }

        // Tentukan durasi
        int duration = 90;
        try {
          final start = sData['startTime']?.toString() ?? '07:30';
          final end = sData['endTime']?.toString() ?? '09:00';
          final startParts = start.split(':');
          final endParts = end.split(':');
          final startMin = int.parse(startParts[0]) * 60 + int.parse(startParts[1]);
          final endMin = int.parse(endParts[0]) * 60 + int.parse(endParts[1]);
          if (endMin > startMin) {
            duration = endMin - startMin;
          }
        } catch (_) {}

        // Ambil questions dari exam_questions/${eventId}_${subjectId}
        final qDoc = await _db
            .collection('schools')
            .doc(schoolId)
            .collection('exam_questions')
            .doc('${eventId}_$subjectId')
            .get();

        if (qDoc.exists && qDoc.data() != null) {
          final qData = qDoc.data()!;
          final questionsList = qData['questions'] as List? ?? [];

          // Buat ID exam: eventId_subjectId_classId
          final examId = '${eventId}_${subjectId}_$classId';

          // Tulis ke collection /exams
          await _db
              .collection('schools')
              .doc(schoolId)
              .collection('exams')
              .doc(examId)
              .set({
            'title': '$examType $subjectName - $className',
            'description': 'Ujian Semester $examType - $title',
            'classId': classId,
            'className': className,
            'subjectId': subjectId,
            'subjectName': subjectName,
            'teacherId': authorIds.isNotEmpty ? authorIds.first : '',
            'teacherName': authorNames.isNotEmpty ? authorNames.join(', ') : 'Guru Penguji',
            'teacherIds': authorIds,
            'teacherNames': authorNames,
            'durationMinutes': duration,
            'syncToGrades': true,
            'gradeCategory': examType, // UTS atau UAS
            'tahunAjaran': tahunAjaran,
            'semester': semester,
            'createdAt': FieldValue.serverTimestamp(),
            'dueDate': Timestamp.fromDate((sData['date'] as Timestamp).toDate().add(const Duration(days: 1))),
            'status': 'active',
            'questions': questionsList,
            'susulanStudentIds': [],
          });
        }
      }
    }
  }

  /// Hapus event beserta seluruh sesinya (batch delete)
  Future<void> deleteExamEvent(String schoolId, String eventId) async {
    final batch = _db.batch();

    // Hapus semua sesi terkait
    final sessions = await _sessionsRef(schoolId)
        .where('eventId', isEqualTo: eventId)
        .get();
    for (final doc in sessions.docs) {
      batch.delete(doc.reference);
    }

    // Hapus exams yang digenerate oleh event ini
    final examsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('exams')
        .get();
    for (final doc in examsSnap.docs) {
      if (doc.id.startsWith('${eventId}_')) {
        batch.delete(doc.reference);
        // Hapus juga grades terkait
        batch.delete(_db.collection('schools').doc(schoolId).collection('grades').doc(doc.id));
      }
    }

    batch.delete(_eventsRef(schoolId).doc(eventId));
    await batch.commit();
  }

  // ── ExamSession CRUD ─────────────────────────────────────────

  /// Menyimpan list ExamSession hasil generate ke Firestore beserta participations-nya
  Future<void> saveGeneratedSessions(
      String schoolId, List<ExamSession> sessions) async {
    for (final session in sessions) {
      final sessionRef = _sessionsRef(schoolId).doc();
      final batch = _db.batch();
      
      // Simpan session
      batch.set(sessionRef, session.toFirestore());
      
      // Simpan draf presensi & kursi jika ada
      if (session.previewParticipations != null) {
        for (final p in session.previewParticipations!) {
          final pRef = sessionRef.collection('participations').doc(p.studentId);
          batch.set(pRef, p.toFirestore());
        }
      }
      
      await batch.commit();
    }
  }

  /// Stream semua sesi untuk satu event
  Stream<List<ExamSession>> getSessionsByEvent(
      String schoolId, String eventId) {
    return _sessionsRef(schoolId)
        .where('eventId', isEqualTo: eventId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi yang ditugaskan ke pengawas tertentu
  Stream<List<ExamSession>> getSessionsByProctor(
      String schoolId, String proctorId) {
    return _sessionsRef(schoolId)
        .where('proctorId', isEqualTo: proctorId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi yang guru bersangkutan menjadi author soal
  Stream<List<ExamSession>> getSessionsByAuthor(
      String schoolId, String authorTeacherId) {
    return _sessionsRef(schoolId)
        .where('authorTeacherId', isEqualTo: authorTeacherId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Stream sesi untuk kelas tertentu (untuk kalender siswa)
  Stream<List<ExamSession>> getSessionsByClass(
      String schoolId, String classId) {
    return _sessionsRef(schoolId)
        .where('classId', isEqualTo: classId)
        .snapshots()
        .map((snap) {
          final list = snap.docs.map((d) => ExamSession.fromFirestore(d)).toList();
          list.sort((a, b) => a.date.compareTo(b.date));
          return list;
        });
  }

  /// Admin manual override pengawas
  Future<void> updateSessionProctor({
    required String schoolId,
    required String sessionId,
    required String newProctorId,
    required String newProctorName,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'proctorId': newProctorId,
      'proctorName': newProctorName,
    });
  }

  /// Admin update nama ruangan
  Future<void> updateSessionRoom({
    required String schoolId,
    required String sessionId,
    required String roomName,
  }) async {
    await _sessionsRef(schoolId)
        .doc(sessionId)
        .update({'roomName': roomName});
  }

  /// Pengawas mengaktifkan QR (mulai sesi)
  Future<void> activateSessionQr({
    required String schoolId,
    required String sessionId,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'isQrActive': true,
      'examStatus': 'Active',
    });
  }

  /// Pengawas menutup sesi
  Future<void> finishSession({
    required String schoolId,
    required String sessionId,
  }) async {
    await _sessionsRef(schoolId).doc(sessionId).update({
      'isQrActive': false,
      'examStatus': 'Finished',
    });
  }

  /// Stream satu sesi secara real-time (untuk polling status QR)
  Stream<ExamSession?> getSessionStream(String schoolId, String sessionId) {
    return _sessionsRef(schoolId)
        .doc(sessionId)
        .snapshots()
        .map((d) => d.exists ? ExamSession.fromFirestore(d) : null);
  }

  // ── Participation CRUD ───────────────────────────────────────

  /// Mencatat kehadiran siswa setelah scan QR (idempotent)
  Future<void> recordParticipation({
    required String schoolId,
    required String sessionId,
    required String studentId,
    required String studentName,
    required String nis,
  }) async {
    await _participationsRef(schoolId, sessionId).doc(studentId).set({
      'studentId': studentId,
      'studentName': studentName,
      'nis': nis,
      'scannedAt': FieldValue.serverTimestamp(),
      'hasStarted': false,
    }, SetOptions(merge: true));
  }

  /// Cek apakah siswa sudah scan (untuk gate tombol "Mulai Ujian")
  Future<bool> hasStudentScanned({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    final doc = await _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .get();
    if (!doc.exists) return false;
    return doc.data()?['scannedAt'] != null;
  }

  /// Stream real-time participation siswa tertentu
  Stream<ExamParticipation?> getParticipationStream({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) {
    return _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .snapshots()
        .map((d) => d.exists ? ExamParticipation.fromFirestore(d) : null);
  }

  /// Stream seluruh peserta sesi (untuk proctor dashboard)
  Stream<List<ExamParticipation>> getParticipations({
    required String schoolId,
    required String sessionId,
  }) {
    return _participationsRef(schoolId, sessionId)
        .snapshots()
        .map((snap) =>
            snap.docs.map((d) => ExamParticipation.fromFirestore(d)).toList());
  }

  /// Update status hasStarted siswa setelah mulai ujian
  Future<void> markStudentStarted({
    required String schoolId,
    required String sessionId,
    required String studentId,
  }) async {
    await _participationsRef(schoolId, sessionId)
        .doc(studentId)
        .update({'hasStarted': true});
  }


  // ── Utility ──────────────────────────────────────────────────

  /// Generate UUID v4 sederhana untuk qrToken
  static String generateQrToken() {
    final rng = Random.secure();
    final bytes = List<int>.generate(16, (_) => rng.nextInt(256));
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    String hex(int n) => n.toRadixString(16).padLeft(2, '0');
    return '${hex(bytes[0])}${hex(bytes[1])}${hex(bytes[2])}${hex(bytes[3])}'
        '-${hex(bytes[4])}${hex(bytes[5])}'
        '-${hex(bytes[6])}${hex(bytes[7])}'
        '-${hex(bytes[8])}${hex(bytes[9])}'
        '-${hex(bytes[10])}${hex(bytes[11])}${hex(bytes[12])}${hex(bytes[13])}${hex(bytes[14])}${hex(bytes[15])}';
  }

  // ── Seat Distribution per existing session ────────────────────

  /// Distribusi kursi selang-seling untuk sesi yang sudah ada di Firestore.
  /// Menghapus data participations lama, lalu generate ulang dari daftar rooms yang diberikan.
  /// Algoritma: siswa 2 angkatan berbeda diinterleave (ganjil=angkatan A, genap=angkatan B).
  Future<void> distributeSeatsForExistingSession({
    required String schoolId,
    required String sessionId,
    required String classId,
    required List<ExamRoom> rooms,
  }) async {
    // 1. Fetch students in this class
    final studentsSnap = await _db
        .collection('schools')
        .doc(schoolId)
        .collection('students')
        .where('classId', isEqualTo: classId)
        .get();

    final allStudents = studentsSnap.docs.map((d) {
      final data = d.data();
      return {
        'id': d.id,
        'nama': data['nama'] ?? '',
        'nis': data['nis'] ?? '',
        'angkatan': (data['angkatan'] ?? '').toString().trim(),
      };
    }).toList();

    // 2. Group by angkatan
    final Map<String, List<Map<String, dynamic>>> byAngkatan = {};
    for (final s in allStudents) {
      final a = (s['angkatan'] as String).isNotEmpty ? s['angkatan'] as String : '-';
      byAngkatan.putIfAbsent(a, () => []).add(s);
    }

    // Sort: biggest cohort first for list A
    final sortedAngkatans = byAngkatan.keys.toList()
      ..sort((a, b) => byAngkatan[b]!.length.compareTo(byAngkatan[a]!.length));

    List<Map<String, dynamic>> listA = [];
    List<Map<String, dynamic>> listB = [];

    if (sortedAngkatans.isNotEmpty) {
      listA = List.from(byAngkatan[sortedAngkatans[0]]!)..shuffle();
    }
    if (sortedAngkatans.length > 1) {
      for (int i = 1; i < sortedAngkatans.length; i++) {
        listB.addAll(byAngkatan[sortedAngkatans[i]]!);
      }
      listB.shuffle();
    }

    // 3. Build participation list (interleaved by room)
    final List<ExamParticipation> participations = [];
    int indexA = 0;
    int indexB = 0;

    for (final room in rooms) {
      for (int seat = 1; seat <= room.capacity; seat++) {
        if (indexA >= listA.length && indexB >= listB.length) break;

        Map<String, dynamic>? picked;
        if (seat % 2 != 0) {
          picked = indexA < listA.length ? listA[indexA++] : (indexB < listB.length ? listB[indexB++] : null);
        } else {
          picked = indexB < listB.length ? listB[indexB++] : (indexA < listA.length ? listA[indexA++] : null);
        }

        if (picked != null) {
          participations.add(ExamParticipation(
            studentId: picked['id'] as String,
            studentName: picked['nama'] as String,
            nis: picked['nis'] as String,
            hasStarted: false,
            seatNumber: seat,
            roomName: room.name,
            angkatan: picked['angkatan'] as String,
          ));
        }
      }
    }

    // 4. Batch write: delete old participations, write new
    final pRef = _participationsRef(schoolId, sessionId);

    // Delete existing participations
    final existingDocs = await pRef.get();
    final batch = _db.batch();
    for (final doc in existingDocs.docs) {
      batch.delete(doc.reference);
    }

    // Write new participations
    for (final p in participations) {
      batch.set(pRef.doc(p.studentId), p.toFirestore());
    }

    // Update session roomName
    final roomNameStr = rooms.map((r) => r.name).join(', ');
    batch.update(_sessionsRef(schoolId).doc(sessionId), {'roomName': roomNameStr});

    await batch.commit();
  }
}
