import 'package:cloud_firestore/cloud_firestore.dart';

// ─────────────────────────────────────────────────────────────
//  ExamSlot — satu slot waktu harian (Sesi 1, 2, 3, dst.)
// ─────────────────────────────────────────────────────────────
class ExamSlot {
  final String name;       // e.g. "Sesi 1"
  final String startTime;  // e.g. "07:30"
  final String endTime;    // e.g. "09:30"

  const ExamSlot({
    required this.name,
    required this.startTime,
    required this.endTime,
  });

  factory ExamSlot.fromMap(Map<String, dynamic> map) => ExamSlot(
        name: map['name'] ?? '',
        startTime: map['startTime'] ?? '',
        endTime: map['endTime'] ?? '',
      );

  Map<String, dynamic> toMap() => {
        'name': name,
        'startTime': startTime,
        'endTime': endTime,
      };
}

// ─────────────────────────────────────────────────────────────
//  ExamSubjectConfig — konfigurasi mapel per event UTS/UAS
// ─────────────────────────────────────────────────────────────
class ExamSubjectConfig {
  final String subjectId;
  final String subjectName;
  final String authorTeacherId;   // Pembuat soal → tidak boleh jadi pengawas
  final String authorTeacherName;
  final List<String> classIds;    // Kelas yang mengikuti ujian mapel ini

  const ExamSubjectConfig({
    required this.subjectId,
    required this.subjectName,
    required this.authorTeacherId,
    required this.authorTeacherName,
    required this.classIds,
  });

  factory ExamSubjectConfig.fromMap(Map<String, dynamic> map) => ExamSubjectConfig(
        subjectId: map['subjectId'] ?? '',
        subjectName: map['subjectName'] ?? '',
        authorTeacherId: map['authorTeacherId'] ?? '',
        authorTeacherName: map['authorTeacherName'] ?? '',
        classIds: List<String>.from(map['classIds'] ?? []),
      );

  Map<String, dynamic> toMap() => {
        'subjectId': subjectId,
        'subjectName': subjectName,
        'authorTeacherId': authorTeacherId,
        'authorTeacherName': authorTeacherName,
        'classIds': classIds,
      };
}

// ─────────────────────────────────────────────────────────────
//  ExamRoom — Ruangan ujian & kapasitas kursi
// ─────────────────────────────────────────────────────────────
class ExamRoom {
  final String name;
  final int capacity;
  final List<String> classes;

  const ExamRoom({
    required this.name,
    required this.capacity,
    this.classes = const [],
  });

  ExamRoom copyWith({
    String? name,
    int? capacity,
    List<String>? classes,
  }) {
    return ExamRoom(
      name: name ?? this.name,
      capacity: capacity ?? this.capacity,
      classes: classes ?? this.classes,
    );
  }

  factory ExamRoom.fromMap(Map<String, dynamic> map) => ExamRoom(
        name: map['name'] ?? '',
        capacity: map['capacity'] as int? ?? 0,
        classes: List<String>.from(map['classes'] ?? []),
      );

  Map<String, dynamic> toMap() => {
        'name': name,
        'capacity': capacity,
        'classes': classes,
      };
}

// ─────────────────────────────────────────────────────────────
//  ExamEvent — header event UTS/UAS
//  Koleksi: schools/{schoolId}/exam_events
// ─────────────────────────────────────────────────────────────
class ExamEvent {
  final String id;
  final String title;          // e.g. "UAS Semester 1 2025/2026"
  final String examType;       // "UTS" | "UAS"
  final DateTime startDate;
  final DateTime endDate;
  final List<ExamSlot> dailySlots;
  final List<ExamSubjectConfig> subjectConfigs;
  final List<ExamRoom> rooms;  // Ruangan yang dipakai untuk ujian
  final String examStatus;     // "Planning" | "Active" | "Finished"
  final bool isAutoGenerated;
  final DateTime createdAt;

  const ExamEvent({
    required this.id,
    required this.title,
    required this.examType,
    required this.startDate,
    required this.endDate,
    required this.dailySlots,
    required this.subjectConfigs,
    required this.rooms,
    required this.examStatus,
    required this.isAutoGenerated,
    required this.createdAt,
  });

  factory ExamEvent.fromFirestore(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? {};
    return ExamEvent(
      id: doc.id,
      title: data['title'] ?? '',
      examType: data['examType'] ?? 'UTS',
      startDate: (data['startDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      endDate: (data['endDate'] as Timestamp?)?.toDate() ?? DateTime.now(),
      dailySlots: (data['dailySlots'] as List? ?? [])
          .map((s) => ExamSlot.fromMap(Map<String, dynamic>.from(s)))
          .toList(),
      subjectConfigs: (data['subjectConfigs'] as List? ?? [])
          .map((c) => ExamSubjectConfig.fromMap(Map<String, dynamic>.from(c)))
          .toList(),
      rooms: (data['rooms'] as List? ?? [])
          .map((r) => ExamRoom.fromMap(Map<String, dynamic>.from(r)))
          .toList(),
      examStatus: data['examStatus'] ?? 'Planning',
      isAutoGenerated: data['isAutoGenerated'] as bool? ?? false,
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toFirestore() => {
        'title': title,
        'examType': examType,
        'startDate': Timestamp.fromDate(startDate),
        'endDate': Timestamp.fromDate(endDate),
        'dailySlots': dailySlots.map((s) => s.toMap()).toList(),
        'subjectConfigs': subjectConfigs.map((c) => c.toMap()).toList(),
        'rooms': rooms.map((r) => r.toMap()).toList(),
        'examStatus': examStatus,
        'isAutoGenerated': isAutoGenerated,
        'createdAt': Timestamp.fromDate(createdAt),
      };

  ExamEvent copyWith({
    String? title,
    String? examType,
    DateTime? startDate,
    DateTime? endDate,
    List<ExamSlot>? dailySlots,
    List<ExamSubjectConfig>? subjectConfigs,
    List<ExamRoom>? rooms,
    String? examStatus,
    bool? isAutoGenerated,
  }) {
    return ExamEvent(
      id: id,
      title: title ?? this.title,
      examType: examType ?? this.examType,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      dailySlots: dailySlots ?? this.dailySlots,
      subjectConfigs: subjectConfigs ?? this.subjectConfigs,
      rooms: rooms ?? this.rooms,
      examStatus: examStatus ?? this.examStatus,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt,
    );
  }
}

// ─────────────────────────────────────────────────────────────
//  ExamSession — satu sesi ujian (mapel + kelas + slot + pengawas)
//  Koleksi: schools/{schoolId}/exam_sessions
// ─────────────────────────────────────────────────────────────
class ExamSession {
  final String id;
  final String eventId;
  final String subjectId;
  final String subjectName;
  final String classId;
  final String className;
  final DateTime date;
  final String slotName;
  final String startTime;
  final String endTime;
  final String roomName;
  final String proctorId;       // teacherDocId pengawas
  final String proctorName;
  final String authorTeacherId; // pembuat soal
  final String qrToken;         // UUID unik untuk validasi scan siswa
  final bool isQrActive;        // diaktifkan pengawas saat sesi dimulai
  final String examStatus;      // "Scheduled" | "Active" | "Finished"
  final List<ExamParticipation>? previewParticipations; // NEW: preview only

  const ExamSession({
    required this.id,
    required this.eventId,
    required this.subjectId,
    required this.subjectName,
    required this.classId,
    required this.className,
    required this.date,
    required this.slotName,
    required this.startTime,
    required this.endTime,
    required this.roomName,
    required this.proctorId,
    required this.proctorName,
    required this.authorTeacherId,
    required this.qrToken,
    required this.isQrActive,
    required this.examStatus,
    this.previewParticipations,
  });

  factory ExamSession.fromFirestore(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? {};
    return ExamSession(
      id: doc.id,
      eventId: data['eventId'] ?? '',
      subjectId: data['subjectId'] ?? '',
      subjectName: data['subjectName'] ?? '',
      classId: data['classId'] ?? '',
      className: data['className'] ?? '',
      date: (data['date'] as Timestamp?)?.toDate() ?? DateTime.now(),
      slotName: data['slotName'] ?? '',
      startTime: data['startTime'] ?? '',
      endTime: data['endTime'] ?? '',
      roomName: data['roomName'] ?? '',
      proctorId: data['proctorId'] ?? '',
      proctorName: data['proctorName'] ?? '',
      authorTeacherId: data['authorTeacherId'] ?? '',
      qrToken: data['qrToken'] ?? '',
      isQrActive: data['isQrActive'] as bool? ?? false,
      examStatus: data['examStatus'] ?? 'Scheduled',
    );
  }

  Map<String, dynamic> toFirestore() => {
        'eventId': eventId,
        'subjectId': subjectId,
        'subjectName': subjectName,
        'classId': classId,
        'className': className,
        'date': Timestamp.fromDate(date),
        'slotName': slotName,
        'startTime': startTime,
        'endTime': endTime,
        'roomName': roomName,
        'proctorId': proctorId,
        'proctorName': proctorName,
        'authorTeacherId': authorTeacherId,
        'qrToken': qrToken,
        'isQrActive': isQrActive,
        'examStatus': examStatus,
      };

  ExamSession copyWith({
    String? proctorId,
    String? proctorName,
    String? roomName,
    bool? isQrActive,
    String? examStatus,
    List<ExamParticipation>? previewParticipations,
  }) {
    return ExamSession(
      id: id,
      eventId: eventId,
      subjectId: subjectId,
      subjectName: subjectName,
      classId: classId,
      className: className,
      date: date,
      slotName: slotName,
      startTime: startTime,
      endTime: endTime,
      roomName: roomName ?? this.roomName,
      proctorId: proctorId ?? this.proctorId,
      proctorName: proctorName ?? this.proctorName,
      authorTeacherId: authorTeacherId,
      qrToken: qrToken,
      isQrActive: isQrActive ?? this.isQrActive,
      examStatus: examStatus ?? this.examStatus,
      previewParticipations: previewParticipations ?? this.previewParticipations,
    );
  }
}

// ─────────────────────────────────────────────────────────────
//  ExamParticipation — presensi siswa untuk satu sesi
//  Subkoleksi: exam_sessions/{sessionId}/participations/{studentId}
// ─────────────────────────────────────────────────────────────
class ExamParticipation {
  final String studentId;
  final String studentName;
  final String nis;
  final DateTime? scannedAt;
  final bool hasStarted;
  final int seatNumber;
  final String roomName;
  final String angkatan;

  const ExamParticipation({
    required this.studentId,
    required this.studentName,
    required this.nis,
    this.scannedAt,
    required this.hasStarted,
    required this.seatNumber,
    required this.roomName,
    required this.angkatan,
  });

  factory ExamParticipation.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? {};
    return ExamParticipation(
      studentId: doc.id,
      studentName: data['studentName'] ?? '',
      nis: data['nis'] ?? '',
      scannedAt: (data['scannedAt'] as Timestamp?)?.toDate(),
      hasStarted: data['hasStarted'] as bool? ?? false,
      seatNumber: data['seatNumber'] as int? ?? 0,
      roomName: data['roomName'] ?? '',
      angkatan: data['angkatan'] ?? '',
    );
  }

  Map<String, dynamic> toFirestore() => {
        'studentId': studentId,
        'studentName': studentName,
        'nis': nis,
        if (scannedAt != null) 'scannedAt': Timestamp.fromDate(scannedAt!),
        'hasStarted': hasStarted,
        'seatNumber': seatNumber,
        'roomName': roomName,
        'angkatan': angkatan,
      };
}
